avi_config:
  pool:
    - name: oid-pool
      cloud_ref: /api/cloud?name=LM-Paris
      tenant_ref: /api/tenant?name=admin
      vrf_ref: /api/vrfcontext?name=T1-Paris
      tier1_lr: "{{ T1_Paris_Path }}"
      health_monitor_refs:
      - /api/healthmonitor?name=oid-hm
      lb_algorithm: "LB_ALGORITHM_ROUND_ROBIN"
      servers:
      - hostname: 10.10.10.10
        ip:
          addr: 10.10.10.10
          type: V4
    - name: secure-bi-pool
      cloud_ref: /api/cloud?name=LM-Paris
      tenant_ref: /api/tenant?name=admin
      vrf_ref: /api/vrfcontext?name=T1-Paris
      tier1_lr: "{{ T1_Paris_Path }}"
      health_monitor_refs:
      - /api/healthmonitor?name=bi-hm
      lb_algorithm: "LB_ALGORITHM_ROUND_ROBIN"
      servers:
      - hostname: 20.20.20.20
        ip:
          addr: 20.20.20.20
          type: V4
      ssl_profile_ref: /api/sslprofile?name=System-Standard

  healthmonitor:
    - name: oid-hm
      failed_checks: 3
      successful_checks: 3
      http_monitor:
        http_request: GET /status.html HTTP/1.0
        http_response_code:
        - HTTP_2XX
      tenant_ref: /api/tenant?name=admin
      type: HEALTH_MONITOR_HTTP
    - name: bi-hm
      failed_checks: 3
      successful_checks: 3
      https_monitor:
        http_request: GET /xmlpserver/services HTTP/1.1
        http_response: And now... Some Services
        http_request_body: "HTTP/1.1\r\nHost: \r\nConnection: Close \r\n\r\n"
        http_response_code:
        - HTTP_2XX
      tenant_ref: /api/tenant?name=admin
      type: HEALTH_MONITOR_HTTPS
